"""update2 Products model

Revision ID: a2f381c334bb
Revises: eba44d021ef4
Create Date: 2026-07-09 14:36:44.181487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2f381c334bb'
down_revision: Union[str, Sequence[str], None] = 'eba44d021ef4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_visible', sa.Boolean(), server_default='TRUE', nullable=False))
    op.drop_column('products', 'is_visable')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_visable', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_column('products', 'is_visible')
    # ### end Alembic commands ###
